### ISSUE TITLE
Update to Spring Boot 2.6.x and Java 17

### ISSUE THREAD

**Issue by tboeghk** [observabilitystack/geoip-api#77]
Updating to Spring Boot 2.6.x and the matching native libraries is tracked in the [`feature/spring-boot-2.6`](https://github.com/observabilitystack/geoip-api/tree/feature/spring-boot-2.6) branch.

During startup we use the `@ConditionalOnProperty` annotation to distinguish, which database file to load. This behaviour is currently broken for the native image. This is tracked in spring-projects-experimental/spring-native#1367

**Comment by tboeghk** [comment]
The error still persists and unfortunately will be fixed in Spring 3.x onwards :-(

```
2022-04-05 15:47:36.385  WARN 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'geoIpRestController': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cityProvider': Unexpected exception during bean creation; nested exception is org.springframework.beans.factory.BeanInitializationException: Neither CITY_DB_FILE nor ASN_DB_FILE nor ISP_DB_FILE given
2022-04-05 15:47:36.385  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2022-04-05 15:47:36.387 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'geoIpRestController': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cityProvider': Unexpected exception during bean creation; nested exception is org.springframework.beans.factory.BeanInitializationException: Neither CITY_DB_FILE nor ASN_DB_FILE nor ISP_DB_FILE given
	at org.springframework.aot.beans.factory.InjectedConstructionResolver.resolve(InjectedConstructionResolver.java:88) ~[na:na]
	at org.springframework.aot.beans.factory.InjectedElementResolver.resolve(InjectedElementResolver.java:35) ~[na:na]
```

**Comment by tboeghk** [comment]
Finally Spring 3 arrived and it has happened: The `native` image is now the default release.
